// Contactos iniciales (seed) de la agenda, tomados del directorio institucional.
// Formato compacto por fila: [unidad, cargo, nombre, telefono, correo].
// Se cargan una sola vez; luego cada usuario los edita/borra libremente.
export const AGENDA_SEED = [
  ["Cesfam Algarrobo - Emergencia","","","974986267",""],
  ["Cesfam El Tabo - Emergencia","","","442351300",""],
  ["Cesfam El Tabo - Emergencia","","","4561008",""],
  ["HCVB - Mesa Central","","","324000",""],
  ["HCVB - Mesa Central","","","324001",""],
  ["HCVB - Mesa Central","","","324401",""],
  ["HCVB - Neurocirugía","","","324461","neurocirugia2.hcvb@redsalud.gov.cl"],
  ["HCVB - Oncología","Secretaria","","324521",""],
  ["HCVB - Archivo Rayos","","","324773",""],
  ["HCVB - Archivo Rayos","","","324665",""],
  ["HCVB - Jefa De Agenda","","Carolina Cid","324892",""],
  ["HCVB - Imagenología","Enfermera","Carolina Guerrero","324410","carolina.guerreroc@redsalud.gov.cl"],
  ["HCVB - Medicina nuclear","","Carolina Leiva","327808","carolinaleival@redsalud.gov.cl"],
  ["HCVB - Archivo","Jefatura","Claudia Yañez","324350","claudia.yanez@redsalud.gov.cl"],
  ["HCVB - Medicina Nuclear","Jefatura","Francisca Araya","324569","francisca.arayaalvarez@redsalud.gov.cl"],
  ["HCVB - Oncología","Jefatura","Katty Yuinnissi","324587","katty.yunnissi@redsalud.gov.cl"],
  ["HCVB - Emergencia","Secretaria","Maria Paz Perez","324137","mariapaz.perez@redsalud.gov.cl"],
  ["HCVB - Informatica","","Mauricio Jerez","324825",""],
  ["HCVB - Medicina nuclear","Jefatura","Mauricio Troncoso","327867",""],
  ["HCVB - Imagenología","Jefatura","Maximiliano Godoy","324080","maximiliano.godoy@redsalud.gob.cl"],
  ["HEP - Mesa Central","","","327403",""],
  ["HEP - OIRS","","","327407",""],
  ["HEP - Calidad","","Florencia Ramirez","327516",""],
  ["HEP - Estadística","","Julia","238400",""],
  ["Hospital El Salvador - Some","","Rodrigo Silva","327246",""],
  ["HCV - Calidad","","Daniela Ibarra","353097","daniela.ibarra@redsalud.gob.cl"],
  ["HCV - Agenda Médica","Agenda","Alan Rojas","353112","alan.rojas@redsalud.gob.cl"],
  ["HCV - Agenda Médica","Agenda","Ana Karina Obando","353025",""],
  ["HCV - Agenda Médica","Citaciones","Bastian Ramirez","356438",""],
  ["HCV - Agenda Médica","Agenda","Claudia Riquelme","356271","claudia.riquelme.r@redsalud.gob.cl"],
  ["HCV - Agenda Médica","Citaciones","Daisy Cid","353114",""],
  ["HCV - Agenda Médica","Jefatura","Fernando Cortes Barros","356263","fernando.cortesb@redsalud.gob.cl"],
  ["HCV - Agenda Médica","Agenda Y Coordinación","Gabriela Jorquera","353110","coordinacion3.hcv@redsalud.gob.cl"],
  ["HCV - Agenda Médica","Agenda","Gisela Malhue","356270","gisela.malhue.n@redsalud.gob.cl"],
  ["HCV - Agenda Médica","Agenda","Gisela Malhue","356368","gisela.malhue.n@redsalud.gob.cl"],
  ["HCV - Agenda Médica","Agenda","Javiera Mora","353023",""],
  ["HCV - Agenda Médica","Citaciones","Jessy Tilleria","356436","jessy.tilleria@redsalud.gob.cl"],
  ["HCV - Agenda Médica","Agenda","Katty Angulo","356269","katty.angulo.d@redsalud.gob.cl"],
  ["HCV - Agenda Médica","Agenda","Nahiry Fernandez","356456","nahiry.fernandez.h@redsalud.gob.cl"],
  ["HCV - Agenda Médica","Agenda","Paola Garcia","353020",""],
  ["HCV - Agenda Médica","Agenda","Paula Reyes","356187",""],
  ["HCV - Agenda Médica","Citaciones","Yessica Araya","353111",""],
  ["HCV - Anatomía Patológica","Secretaria","Cynthia Ponce Nuñez","356328","cynthia.ponce@redsalud.gob.cl"],
  ["HCV - Anatomía Patológica","Jefatura","Dr. Juan Manuel Moncaleano","353218","juan.moncaleano.a@redsalud.gob.cl"],
  ["HCV - Anatomía Patológica","Secretaria","Javiera Salinas","356328","javiera.salinasf@redsalud.gob.cl"],
  ["HCV - Anatomía Patológica","TM Supervisor","Roberto Ramos Diaz","356329","roberto.ramos@redsalud.gob.cl"],
  ["HCV - Anatomía Patológica","Encargada Morgue","Romina Silva Zuñiga","356183","romina.silva@redsalud.gob.cl"],
  ["HCV - Archivo","Archivo","Ana Alvarado Farias","353102","ana.alvarado@redsalud.gob.cl"],
  ["HCV - Archivo","Archivos generales -1","","353109",""],
  ["HCV - Archivo","Jefatura","Elisabeth Moreno Rojas","356274","elisabeth.moreno@redsalud.gob.cl"],
  ["HCV - Archivo","Archivo Hospital Antiguo","Esteban Quiroz","356264",""],
  ["HCV - Archivo","Archivo Poli","Mariana Araya","356266","romina.diaz.s@redsalud.gob.cl"],
  ["HCV - Archivo","Archivo Solicitudes / Sala","Silvia Donoso/Romina Diaz","356265","silvia.donoso@redsalud.gob.cl"],
  ["HCV - Archivo","Archivo Recepcion Fichas Clinicas","Ventanilla Recepcion","353099","archivoreserva2.hcv@redsalud.gob.cl"],
  ["HCV - Auditoría","Jefatura","Carla Farias","356180","carla.farias@redsalud.gob.cl"],
  ["HCV - Auditoría","Jefatura","Pedro Sepulveda","356180","pedro.sepulvedaj@redsalud.gob.cl"],
  ["HCV - CAE","Estacion Medicina","","356379",""],
  ["HCV - CAE","Estacion Medicina","","356389",""],
  ["HCV - CAE","Oftalmología","","356352",""],
  ["HCV - CAE","Oftalmología","","353057",""],
  ["HCV - CAE","Gineco-obstetra Pasillo","","356355",""],
  ["HCV - CAE","Procedimiento Urológico","Alejandra Gutierrez","353073",""],
  ["HCV - CAE","Traumatología","Box 3","353075","luz.rubilar@redsalud.gob.cl"],
  ["HCV - CAE","Recepción paciente ala sur","Carmen Zegers Arancibia","353050",""],
  ["HCV - CAE","Enfermera Neurología Piso -1","Carolina Carreño Araya","353062","neurologia.hcv2024@gmail.com"],
  ["HCV - CAE","Curaciones","Carolina Hernandez","356267","carolinahernandez.f@redsalud.gob.cl"],
  ["HCV - CAE","UNACESS Matrona","Catalina Hernandez Jorquera","356354","catalina.hernandez@redsalud.gob.cl"],
  ["HCV - CAE","Pediatria","Cristian Oyarce","353011",""],
  ["HCV - CAE","Cardiología","Dra. Abigail Peña","356054","abigail.pena@redsalud.gob.cl"],
  ["HCV - CAE","Jefatura","Dra. Christabel Jensen","356165","christabel.jensen@redsalud.gob.cl"],
  ["HCV - CAE","Cardiología","Ecocardiograma","356136",""],
  ["HCV - CAE","Cardiología","Enfermera","356452",""],
  ["HCV - CAE","Gineco-obstetra Ecografía","Franchesca Ramos","356349","franchesca.ramos.s@redsalud.gob.cl"],
  ["HCV - CAE","Procedimiento Urológico - Enfermera","Franchesca Vidal","353064","franchesca.vidal.c@redsalud.gob.cl"],
  ["HCV - CAE","Ginecología","Ginecologia","356229",""],
  ["HCV - CAE","Recepción Paciente Ala Sur","Hector Freire","353050",""],
  ["HCV - CAE","Traumatología - enfermera","Jacqueline Guerrero","353076","jacqueline.guerrero@redsalud.gob.cl"],
  ["HCV - CAE","Traumatología - secretaria","Luz Rubilar","353070","luz.rubilar@redsalud.gob.cl"],
  ["HCV - CAE","Enfermera Supervisora","Magaly Soto","353037","magaly.sotor@redsalud.gob.cl"],
  ["HCV - CAE","Cardiología","Medico","353021",""],
  ["HCV - CAE","Gineco-obstetra Matrona Supervisora","Natalia Cepeda","356346","natalia.cepeda.s@redsalud.gob.cl"],
  ["HCV - CAE","Secretaria","Patricia Farias Lemos","356341","patricia.farias@redsalud.gob.cl"],
  ["HCV - CAE","Unacess TENS","Valentina Soto Rone","353044",""],
  ["HCV - Calidad","Encargada de Calidad","Andrea Sanhueza Novoa","353096","andrea.sanhuezan@redsalud.gob.cl"],
  ["HCV - Calidad","Enfermera","Francisca Soto Godoy","356369","francisca.soto.g@redsalud.gob.cl"],
  ["HCV - Calidad","Administrativa","Lisbet Peñailillo Seguel","356369","lisbet.penalillo@redsalud.gob.cl"],
  ["HCV - Calidad","Enfermera","Maria Paulina Silva","356369","mariapaulina.silva.p@redsalud.gob.cl"],
  ["HCV - Bienestar","Jefatura","Alejandra Vega Cabrera","356245","alejandra.vega@redsalud.gob.cl"],
  ["HCV - Bienestar","Secretaria","Joan Manzo Bastias","356176","bienestar.hcv@redsalud.gob.cl"],
  ["HCV - Bienestar","Educadora De Parvulos","Karla Farias Gutierrez","353093","karla.farias.g@redsalud.gob.cl"],
  ["HCV - Bienestar","Trabajadora Social","Marcela Araos","356245","marcela.araos@redsalud.gob.cl"],
  ["HCV - Bienestar","Trabajador Social","Nicolas Diaz Jara","356245","nicolas.diaz.j@redsalud.gob.cl"],
  ["HCV - Bienestar","Psicóloga (s)","Orietta Quinteros Nordio","353093","orietta.quinteros.n@redsalud.gob.cl"],
  ["HCV - Capacitación","Administrativo","Ambar Espina","356295",""],
  ["HCV - Capacitación","Secretaria","Nicole Toledo","356295","nicole.toledo@redsalud.gob.cl"],
  ["HCV - Capacitación","Jefatura","Ximena Sanchez","356359","ximena.sanchez.e@redsalud.gob.cl"],
  ["HCV - Alimentación","Manipuladoras de Alimentos","Bodega Central de Alimentacion","356391",""],
  ["HCV - Alimentación","Nutricion Tercer Piso","Daniela Godoy","356393",""],
  ["HCV - Alimentación","Nutricion Cuarto Piso","Luisa Reyes","356394",""],
  ["HCV - Alimentación","Manipuladoras de Alimentos","Manipuladoras de alimentos","356392",""],
  ["HCV - Alimentación","Jefatura","Melissa Barraza","356390","melissa.barraza@redsalud.gob.cl"],
  ["HCV - Alimentación","Nutricion Tercer Piso","Sebastian Quintanilla","356393","sebastian.quintanilla@redsalud.gov.cl"],
  ["HCV - Ciclo De Vida Laboral","Jefatura","Paz Campos","356216","paz.campos@redsalud.gob.cl"],
  ["HCV - Comunicaciones","Comunicaciones","Javiera Gonzalez Galdamez","356195","javieragonzalez@redsalud.gov.cl"],
  ["HCV - Contabilidad","Factura Proveedores","Alejandra Ortiz Rocuant","356211","alejandral.ortiz@redsalud.gob.cl"],
  ["HCV - Contabilidad","Devengo","Andrea Acuña","353080","andrea.acuna@redsalud.gob.cl"],
  ["HCV - Contabilidad","Jefatura","Carmen Gloria Osorio","356210","carmengloria.osorio@redsalud.gob.cl"],
  ["HCV - Contabilidad","Presupuestos","Carmen Luz Marin","356194","carmenluz.marin@redsalud.gob.cl"],
  ["HCV - Contabilidad","Caja 1","Gabriela Perez","356212","gabriela.perez@redsalud.gob.cl"],
  ["HCV - Contabilidad","Devengo","Neda Gutierrez","353081","neda.guitierrez@redsalud.gob.cl"],
  ["HCV - Contabilidad","Pasajes","Oscar Vera","356215","oscar.vera@redsalud.gob.cl"],
  ["HCV - Contabilidad","Inventario","Sergio Gutierrez","356214","sergio.gutierrezc@redsalud.gob.cl"],
  ["HCV - Contabilidad","Caja","Sonia Vega","356213","soniavega@redsalud.gob.cl"],
  ["HCV - Control Centralizado","Jefatura","Bruno Carcher","356258",""],
  ["HCV - Control De Gestión","Analista","Carlos Cameron","353089",""],
  ["HCV - Control De Gestión","Secretaria","Lorena Araya","356166","lorena.araya.c@redsalud.gob.cl"],
  ["HCV - Control De Gestión","Analista De Sistemas","Yaritza Castro Cuevas","353089","yaritza.castro@redsalud.gob.cl"],
  ["HCV - Cuidados Paliativos","Psicologa","Carolina Martinez","353033",""],
  ["HCV - Cuidados Paliativos","Medico Jefe","Dr. Rino Sanchez","353014",""],
  ["HCV - Cuidados Paliativos","Estacion de Enfermeria","Estación de Enfermeria","356347",""],
  ["HCV - Cuidados Paliativos","Enfermera Supervisora","Veronica Arriaza Jeria","353013","veronica.arriaza@redsalud.gob.cl"],
  ["HCV - Dental","Hospital Antiguo","Dr. Andreo/ Dra. Torres","353190","matias.andreo@gmail.com"],
  ["HCV - Dental","Box 1","Dr. Manuel Fernandez Gutierrez","356418","manuel.fernandezg@redsalud.gob.cl"],
  ["HCV - Dental","Box 6","Dr. Nicolas Alvarez Castillo","353030",""],
  ["HCV - Dental","Box 2","Dra. Andrea Perez Zelaya","353028","andrea.perezz@redsalud.gob.cl"],
  ["HCV - Dental","Box 4","Dra. Carolina Cifuentes","353026","carolina.cifuentesc@redsalud.gob.cl"],
  ["HCV - Dental","Jefatura","Dra. Catherine Osorio Rajcevich","353027","catherine.osorio@redsalud.gob.cl"],
  ["HCV - Dental","Hospital Antiguo","Dra. Cifuentes/Dra. Chamorro","356358","katherine.caracciolo.p@redsalud.gov.cl"],
  ["HCV - Dental","Box 3","Dra. Gloria Diaz Araujo","356417","gloria.diaza@redsalud.gob.cl"],
  ["HCV - Dental","Sala Rayos","Dra. Javiera Lopez Vergara","356419","javiera.lopez@redsalud.gob.cl"],
  ["HCV - Dental","Box 5","Dra. Karem Valenzuela","353209","karem.valenzuelac@redsalud.gob.cl"],
  ["HCV - Dental","Recepcion","Katherine Caracciolo","356416","katherine.caracciolo.p@redsalud.gob.cl"],
  ["HCV - Dental","Recepcion","Margaret Castillo","353017",""],
  ["HCV - Desarrollo De Las Personas","Jefatura","Alejandro Parra Reyes","356451","alejandro.parra@redsalud.gob.cl"],
  ["HCV - Diálisis","Secretaria","Daniela Piña","353139","daniela.pina.d@redsalud.gob.cl"],
  ["HCV - Diálisis","Enfermera Supervisora","María Loreto González González","353140","marialoreto.gonzalez.g@redsalud.gob.cl"],
  ["HCV - Dirección","Secretaria","Macarena Lecaros Orellana","356162","macarena.lecaros.o@redsalud.gob.cl"],
  ["HCV - Emergencia Adulto","Admision Urgencia","","353182",""],
  ["HCV - Emergencia Adulto","Sala de Estar de Medicos","","356425",""],
  ["HCV - Emergencia Infantil","Urgencia Pediatrica","","356412",""],
  ["HCV - Emergencia Adulto","Urgencia Adulto","Pasillo","356421",""],
  ["HCV - Emergencia Adulto","Urgencia Adulto","Sala Reanimación","356445",""],
  ["HCV - Emergencia Adulto","Urgencia Adulto","Boarding","356429",""],
  ["HCV - Emergencia Adulto","Secretaria area medica","Barbara Vega","356442","barbara.vegap@redsalud.gob.cl"],
  ["HCV - Emergencia Adulto","Jefatura","Dra. Daily Padron","356185","daily.padron@redsalud.gob.cl"],
  ["HCV - Emergencia Adulto","Enfermero Supervisor","Gabriel Toro","356446","gabriel.toro@redsalud.gob.cl"],
  ["HCV - Emergencia Adulto","Extensión Urgencia Salud Mental","Hospital Antiguo","353055","monica.dagninohcv@gmail.com"],
  ["HCV - Emergencia Adulto","Coordinadora","Katherine Marin Sanchez","356412","katherine.marin.s@redsalud.gob.cl"],
  ["HCV - Emergencia Adulto","Secretaria","Valentina Flores Carvacho","356178","valentina.flores.c@redsalud.gob.cl"],
  ["HCV - Emergencia Gine","Matrona Supervisora","Francheska Farias","353181","francheska.farias.m@redsalud.gob.cl"],
  ["HCV - Emergencia Gine","Recepcion Urgencia","Personal de Turno","356314",""],
  ["HCV - Emergencia Gine","Recepcion Urgencia","Preparto","356315",""],
  ["HCV - Endoscopia","Sala Informe Endoscopia","Dr. Ewaldo Vanderlinder","353059","ewaldo.vanderlinder@redsalud.gob.cl"],
  ["HCV - Endoscopia","Sala Informe Endoscopia","Dr. Miguel Menares","353059","miguel.menares@redsalud.gob.cl"],
  ["HCV - Endoscopia","Sala Informe Endoscopia","Dra. Elizabeth Garcia","353059","elizabeth.gaciab@redsalud.gob.cl"],
  ["HCV - Endoscopia","Enfermera Endoscopia","Maria Fernandez","353061","maria.fernandezmu@redsalud.gob.cl"],
  ["HCV - Endoscopia","Secretaria","Paulina Marquez","356350","paulina.marquez.si@redsalud.gob.cl"],
  ["HCV - Endoscopia","Sala Recuperacion Endoscopia","Tens Endoscopia","353063",""],
  ["HCV - Equipos Médicos","Profesional","Esteban Flores R.","356407","esteban.floresr@redsalud.gob.cl"],
  ["HCV - Equipos Médicos","Administrativo","Maria Jose Duarte","356339","mariajose.duarte@redsalud.gob.cl"],
  ["HCV - Equipos Médicos","Jefatura","Rodrigo Piña","356407","rodrigo.pina@redsalud.gob.cl"],
  ["HCV - Estadística","Monitoreo At Odontológica e Interv. Quirúrgicas","Graciela Vera Jeldres","356279","graciela.vera.j@redsalud.gob.cl"],
  ["HCV - Estadística","Censo y procesos del IEEH-Atencion Cerrada","Jael Cornejo Pardo","356278","jael.cornejo.p@redsalud.gob.cl"],
  ["HCV - Estadística","Confirmación y monitoreo At. Ambulatoria","Lisette Pontigo Fajardo","356277","lissete.pontigo.f@redsalud.gob.cl"],
  ["HCV - Estadística","Monitoreo At. de Urgencia","Maria Casas-Cordero","353095","maria.casascordero@redsalud.gob.cl"],
  ["HCV - Estadística","Jefatura","O. Patricia Paredes Salinas","356275","patricia.paredess@redsalud.gob.cl"],
  ["HCV - Esterilización","Jefatura","Claudia Paredes","353090","claudia.paredes.s@redsalud.gob.cl"],
  ["HCV - Esterilización","Entrega Material Esteril","Entrega Material Esteril","353086","juanamaria.leiva@redsalud.gob.cl"],
  ["HCV - Esterilización","Secretaria","Juana Maria Leiva","356395","juanamaria.leiva@redsalud.gob.cl"],
  ["HCV - Esterilización","Preparación Material Estéril","Juana Maria Leiva O.","356396","juanamaria.leiva@redsalud.gob.cl"],
  ["HCV - Esterilización","Recepcion Material Sucio","Tens","353145","claudia.paredes.s@redsalud.gob.cl"],
  ["HCV - Farmacia","Farmacia Central - Quimico Farmaceutico","Daniela Correia Díaz","356439","daniela.correia@redsalud.gob.cl"],
  ["HCV - Farmacia","Farmacia CAE - Quimico Famaceutico","Diego Castillo","356383","diego.castillo.c@redsalud.gob.cl"],
  ["HCV - Farmacia","Bodega Insumos","Maria Manola Lima","356386","mariamanola.lima@redsalud.gob.cl"],
  ["HCV - Farmacia","Bodega Insumos","Marianela Vidal","356386","marianela.vidal@redsalud.gob.cl"],
  ["HCV - Farmacia","Farmacia Central - Quimico Farmaceutico (S)","Melissa Santander","353122","melissa.santander.m@redsalud.gob.cl"],
  ["HCV - Farmacia","Secretaria","Ninoska Reyes","356382","ninoska.reyes.c@redsalud.gob.cl"],
  ["HCV - Farmacia","Farmacia Cae - Químico Farmacéutico","Q.F. Christopher Sepúlveda","356255","christopher.sepulveda.m@redsalud.gob.cl"],
  ["HCV - Farmacia","Bodega Farmacos - Quimico Farmaceutico","Rodrigo Godoy","356385","rodrigo.godoysantos@redsalud.gov.cl"],
  ["HCV - Farmacia","Farmacia Central - Jefe (S)","Sebastian Caro","356380","sebastian.caro.p@redsalud.gob.cl"],
  ["HCV - Farmacia","Farmacia Central - Quimico Farmaceutico/turno","Sebastian Galvez","356439","sebastian.galvez.r@redsalud.gov.cl"],
  ["HCV - Farmacia","Encargada Proa - Quimico Farmaceutico","Tania Ramos","","tania.ramos.m@redsalud.gob.cl"],
  ["HCV - Farmacia","Farmacia Central","Tens","356381",""],
  ["HCV - Gremios","Aprus","","356188","aprus.hcv@redsalud.gob.cl"],
  ["HCV - Gremios","Fenats","","356189","fenats.hcv@redsalud.gob.cl"],
  ["HCV - Gremios","Afutens","Afutens","356173","afutens.hcv@redsalud.gov.cl"],
  ["HCV - GES","Oftalmologia","Blanca Berrios","353049","blanca.berrios@redsalud.gob.cl"],
  ["HCV - GES","Gestora","Carol Muñoz","356285","carol.enfermerahcv@gmail.com"],
  ["HCV - GES","Monitor GES","Elizabeth Herrera","353022","monitorsigges.hcv@redsalud.gob.cl"],
  ["HCV - GES","Administrativo","Gloria Freire","356283","gloria.freire@redsalud.gob.cl"],
  ["HCV - GES","Salud Mental","Ignacio Herrera","356047","ignacioherrera.ges@gmail.com"],
  ["HCV - GES","Gestora","Lorena Medina","353136","lorena.medina.a@redsalud.gob.cl"],
  ["HCV - GES","Urologia, Ginecologia","Natalia Acuña","356282","natalia.acunag@redsalud.gob.cl"],
  ["HCV - GES","Gestora","Paula Eyzaguirre","353048","paula.eyzaguirre@gmail.com"],
  ["HCV - GES","Neurologia, Dental","Robert Toro","356286","robert.toro@redsalud.gob.cl"],
  ["HCV - GES","Oftalmologia","Valeska Herrera","356440","valeska.herrera@redsalud.gob.cl"],
  ["HCV - GES","Administrativo","Viviana Naranjo","356287","viviana.naranjo@redsalud.gob.cl"],
  ["HCV - Gestión Clínica","Jefatura","Dr. Jorge Revuelta","353155","jorge.revuelta@redsalud.gob.cl"],
  ["HCV - Gestión De Camas","Enfermera","Gestor de turno","356324","gestioncamas.hcv@redsalud.gob.cl"],
  ["HCV - Gestión De Camas","Enfermera","Johana Gavilan","356190","johana.gavilan@redsalud.gob.cl"],
  ["HCV - Abastecimiento","Ejecutiva de compras","Denisse Rojas","356208","denisse.rojaso@redsalud.gob.cl"],
  ["HCV - Abastecimiento","Ejecutiva de compras","Elizabeth Contreras","356205","elizabeth.contreras@redsalud.gob.cl"],
  ["HCV - Abastecimiento","Ejecutivo de compras","Felipe Abarca","356203","felipe.abarca@redsalud.gob.cl"],
  ["HCV - Abastecimiento","Administrativo","Guillermo Gonzales Espinoza","353084","guillermo.gonzales@redsalud.gob.cl"],
  ["HCV - Abastecimiento","Jefatura","Javier Rojas","356200",""],
  ["HCV - Abastecimiento","Ejecutivo de compras","Juan Acevedo","356207","juan.acevedo@redsalud.gov.cl"],
  ["HCV - Abastecimiento","Ejecutivo de compras","Lorena Cortes","356202","lorena.cortes@redsalud.gob.cl"],
  ["HCV - Abastecimiento","Ejecutivo de compras","Luisa Garcia","356207","luisa.garcias@redsalud.gob.cl"],
  ["HCV - Abastecimiento","Ejecutiva De Compras","Pamela Maldonado","356208","pamela.maldonadop@redsalud.gob.cl"],
  ["HCV - Abastecimiento","Secretaria","Priscila Campos","356204","priscila.campos.m@redsalud.gob.cl"],
  ["HCV - Abastecimiento","Bodega Despacho","Ximena Alvarez","356206","ximena.alvarez@redsalud.gob.cl"],
  ["HCV - Gestión De La Información","Programación Medica","Carolina Orellana Torres","356388","carolina.orellana.t@redsalud.gob.cl"],
  ["HCV - Gestión De La Información","Jefatura","Roberto Pinochet","353092","roberto.pinochet@redsalud.gob.cl"],
  ["HCV - Gestión De La Información","Jefe Subdepto. Gestión De La Demanda","Victor Soto","356164","victor.sotoz@redsalud.gob.cl"],
  ["HCV - Gestión De Las Personas","Jefatura","Ana Maria Gonzalez Tobar","353156","anamaria.gonzalez@redsalud.gob.cl"],
  ["HCV - Gestión De Las Personas","Honorarios","Carmen Gloria Velasquez","353079","carmen.velasquez@redsalud.gob.cl"],
  ["HCV - Gestión De Las Personas","Sueldos","Catalina Araya","356231","catalina.araya@redsalud.gob.cl"],
  ["HCV - Gestión De Las Personas","Secretaria","Cherie Morales","353046","personalsecre.hcv@redsalud.gob.cl"],
  ["HCV - Gestión De Las Personas","Contratos","Cindy Ortiz","356299","cindy.ortiz@redsalud.gob.cl"],
  ["HCV - Gestión De Las Personas","Administrativo","Claudia Salazar Moraga","356230","claudia.salazarm@redsalud.gob.cl"],
  ["HCV - Gestión De Las Personas","Administrativo","Contratos","-","dainira.donoso.s@redsalud.gov.cl"],
  ["HCV - Gestión De Las Personas","Encargada De Honorarios Medicos","Elizabeth Carrasco Torres","356233","elizabeth.carrascot@redsalud.gob.cl"],
  ["HCV - Gestión De Las Personas","Ley Médica","Mariela Ramirez","353077","mariela.ramirezr@redsalud.gov.cl"],
  ["HCV - Gestión De Las Personas","Administrativo","Marisol Perez","356411","marisol.perezc@redsalud.gob.cl"],
  ["HCV - Gestión De Las Personas","Profesional","Nadia Quiroga","353078","nadia.quiroga@redsalud.gov.cl"],
  ["HCV - Gestión De Las Personas","Asistencia","Rosa Mendez Perez","356177","rosa.mendez.p@redsalud.gob.cl"],
  ["HCV - Lista Espera","Enfermera","Camila Alarcon","356280","unidadprequirurgica.hcv@gmail.com"],
  ["HCV - Lista Espera","Administrativa","Carmen Angulo","356454","carmen.angulo@redsalud.gob.cl"],
  ["HCV - Lista Espera","Administrativa","Jimena Navarrete","356455","jimena.navarrete@redsalud.gov.cl"],
  ["HCV - Lista Espera","Enfermera","Lucy Nuñez","356443","Lucy.nunez@redsalud.gob.cl"],
  ["HCV - Lista Espera","Jefatura","Macarena Caro","356450","macarena.caro@redsalud.gob.cl"],
  ["HCV - Lista Espera","Secretaria","Macarena Salazar","356259","macarena.salazar@redsalud.gob.cl"],
  ["HCV - Lista Espera","Jefatura","Marielle Del Pino Machuca","356288","marielle.delpino@redsalud.gob.cl"],
  ["HCV - Gestión Oncológica","Enfermera","Dahaliana Said","356441","dahaliana.said@redsalud.gob.cl"],
  ["HCV - GRD","Jefatura GRD","Consuelo Tejo","356197","consuelo.tejo@redsalud.gob.cl"],
  ["HCV - GRD","Secretaria","Paulina Espinoza","356179","paulina.espinoza@redsalud.gob.cl"],
  ["HCV - Guardias","Estacion Segundo Piso HCV","","356254",""],
  ["HCV - Guardias","Estacion Urgencia HCV","","356253",""],
  ["HCV - Hospitalización Domiciliaria","Jefatura","Dr. Tarek Ayllach S.","356316","tarek.ayllach.s@redsalud.gob.cl"],
  ["HCV - IAAS","Jefatura","Elsa Flores","356184","elsa.floress@redsalud.gob.cl"],
  ["HCV - IAAS","Epidemiologia","Robert Diaz","353088","robert.diaz@redsalud.gob.cl"],
  ["HCV - IAAS","Epidemiologia","Tania Martinez","353087","iaas.hcv.t@gmail.com"],
  ["HCV - Imagenología","Tecnólogo Supervisor","Cristian Morales Sotomayor","353174","cristian.morales.s@redsalud.gob.cl"],
  ["HCV - Imagenología","Radiólogo","Dr. Fernando Prokes Cisa","356377","fernando.prokes@redsalud.gob.cl"],
  ["HCV - Imagenología","Jefatura","Dra. Bernardita Faundez","356367",""],
  ["HCV - Imagenología","Secretaria Ecografía","Jeanette Gomez","356371",""],
  ["HCV - Imagenología","Mamografía","Katerina Arriola","353187","katerina.arriola@redsalud.gob.cl"],
  ["HCV - Imagenología","Secretaria","Patricia Farias","356376","patricia.fariasb@redsalud.gob.cl"],
  ["HCV - Imagenología","Scanner","Personal de Turno","356447",""],
  ["HCV - Imagenología","Sala Rayos (2)","Personal de Turno","356373",""],
  ["HCV - Imagenología","Sala Rayos (3)","Personal de Turno","353197",""],
  ["HCV - Imagenología","Admisión Atención Ambulatoria","Recepcion","356374",""],
  ["HCV - Imagenología","Recepción Urgencia y Hospitalizados","Recepción Urgencia y Hospitalizados","356372",""],
  ["HCV - Imagenología","Resonancia","Resonancia","353196",""],
  ["HCV - Imagenología","Secretaria Resonancia","Romina Aravena","356370",""],
  ["HCV - Imagenología","Administrador RIS-PACS","Sebastián Maturana","356307",""],
  ["HCV - Ingeniería Informática","soporte","Aquiles Palacios","356366","aquiles.palacios@redsalud.gob.cl"],
  ["HCV - Ingeniería Informática","Soporte / Ciberseguridad","Jose Miguel Astorga","353151","josemiguel.astorga@redsalud.gob.cl"],
  ["HCV - Ingeniería Informática","Soporte","Marco Piña","356403","marco.pina@redsalud.gob.cl"],
  ["HCV - Ingeniería Informática","Jefatura","Nicolas Meyer","356238","eric.mosnich@redsalud.gob.cl"],
  ["HCV - Ingeniería Informática","Secretaria","Oriela Orellana","356400","oriela.orellana@redsalud.gob.cl"],
  ["HCV - Ingeniería Informática","Soporte","Roberto Rojas","356402","roberto.rojasv@redsalud.gob.cl"],
  ["HCV - Ingeniería Operativa","Electricidad","Arnol Silva","356313","arnol.silva@redsalud.gov.cl"],
  ["HCV - Ingeniería Operativa","Infraestructura","Camila Vargas","356313","camila.vargas.vera@redsalud.gob.cl"],
  ["HCV - Ingeniería Operativa","Climatizacion","Cristian Clarke","356313","cristian.clarke@redsalud.gov.cl"],
  ["HCV - Ingeniería Operativa","Equipos Industriales","Karen Castillo","356313","karen.castillom@redsalud.gov.cl"],
  ["HCV - Innovación Y Proyectos","Analista","Alex Martínez C.","353101","alex.martinezc@redsalud.gob.cl"],
  ["HCV - Jurídica","Abogada","Camila Fredes Martinez","356406","camila.fredes.m@redsalud.gob.cl"],
  ["HCV - Jurídica","Abogado","Francisco Nuñez Tapia","353085","francisco.nunez@redsalud.gob.cl"],
  ["HCV - Jurídica","Abogada","Irella Jara Tapia","356406","irella.jara@redsalud.gob.cl"],
  ["HCV - Jurídica","Jefatura","Rodrigo Gonzalez Narvaez","356406","rodrigo.gonzalez@redsalud.gov.cl"],
  ["HCV - Jurídica","Secretaria","Sandra Tobar","356406","sandra.tobar.m@redsalud.gob.cl"],
  ["HCV - Laboratorio","Recepción de Muestras","","356332",""],
  ["HCV - Laboratorio","Sección de Urgencia","","356337",""],
  ["HCV - Laboratorio","Secretaria Bacteriología","","356334",""],
  ["HCV - Laboratorio","Sección Serología","Anais Serrano Bravo","356364","anais.serrano@redsalud.gob.cl"],
  ["HCV - Laboratorio","Sección Tuberculosis","Fernanda Diaz Caceres","356336","fernanda.diaz.c@redsalud.gob.cl"],
  ["HCV - Laboratorio","Sección Uroanálisis","Ingrid Gonzalez Montecino","356335","ingrid.gonzalez@redsalud.gob.cl"],
  ["HCV - Laboratorio","Jefatura","Jorge Yañez","356330","jorged.yanez@redsalud.gov.cl"],
  ["HCV - Laboratorio","Sección Hematología","Jorge Yañez Contreras","356363","jorged.yanez@redsalud.gob.cl"],
  ["HCV - Laboratorio","Secretaria RH Lab.Clínico","Karol Villamizar Castillo","353192","karol.villamizar@redsalud.gob.cl"],
  ["HCV - Laboratorio","Toma De Muestras","Katherine Silva Abarca","353074","tomademuestras.nhcv@gmail.com"],
  ["HCV - Laboratorio","Secretaria de Serología","Patricia Perez Berrios","356362","patricia.perez.b@redsalud.gob.cl"],
  ["HCV - Laboratorio","Sección Bacteriología","Paula Tapia Serano","356331","paula.tapias@redsalud.gob.cl"],
  ["HCV - Laboratorio","Sección Química Clínica","Romina Arenas Sanhueza","356198",""],
  ["HCV - Laboratorio","Encargada de Calidad lab","Vania González Ormeño","356333","vania.gonzalezo@redsalud.gob.cl"],
  ["HCV - Laboratorio","Toma De Muestra","Yohanna Rincón Rojas","356342","tomademuestras.nhcv@gmail.com"],
  ["HCV - Laboratorio Biología Molecular","biología molecular","Diego Diaz Gomez","356414","diego.diaz.g@redsalud.gob.cl"],
  ["HCV - Laboratorio Biología Molecular","biología molecular","Victoria Moya Diaz","356415","victoria.moya@redsalud.gob.cl"],
  ["HCV - Medicina Física Y Rehabilitación","Terapeuta Ocupacional","Carolina Valdes","353131",""],
  ["HCV - Medicina Física Y Rehabilitación","Secretaria Ventanilla","Claudia Fernandez","353127",""],
  ["HCV - Medicina Física Y Rehabilitación","Estacion Kinesiologos","Estacion Kinesiologos","353132",""],
  ["HCV - Medicina Física Y Rehabilitación","Jefatura","Juan Ramon Allendes","356408","juanramon.allendes@redsalud.gob.cl"],
  ["HCV - Medicina Física Y Rehabilitación","Terapeuta Ocupacional","Karina Villatoro","353129","karina.villatoro@redsalud.gob.cl"],
  ["HCV - Medicina Física Y Rehabilitación","Secretaria ventanilla","Maria Joaquina Fernandez","356409","maria.fernandez@redsalud.gob.cl"],
  ["HCV - Medicina Física Y Rehabilitación","Fonoaudiología","Miguelina Soto","356351",""],
  ["HCV - Medicina Física Y Rehabilitación","Trabajadora Social","Veronica Muñoz","353130","veronica.munozp@redsalud.gob.cl"],
  ["HCV - Medicina Transfusional","Laboratorio Inmunohematología","","356360",""],
  ["HCV - Medicina Transfusional","Recepción UMT","","353069",""],
  ["HCV - Medicina Transfusional","Toma De Muestras","","356342",""],
  ["HCV - Medicina Transfusional","UMT","","356361",""],
  ["HCV - Medicina Transfusional","Secretaria UMT","Angelica Munita","353069","angelica.munita@redsalud.gob.cl"],
  ["HCV - Medicina Transfusional","UMT","Entrevista Tecnologo Médico","353068",""],
  ["HCV - Medicina Transfusional","Jefe UMT","Ruben Perez","356345","ruben.perez@redsalud.gob.cl"],
  ["HCV - Navegadores En Red Y Hospital Digital","Administrativa","Estefania Riquelme","356405","estefania.riquelme.p@redsalud.gob.cl"],
  ["HCV - Navegadores En Red Y Hospital Digital","Administrativa","Katherine Zamora","356226","katherine.zamora@redsalud.gob.cl"],
  ["HCV - Navegadores En Red Y Hospital Digital","Jefa Unidad","Loreto Alvear","353167","loreto.alvear.s@redsalud.gob.cl"],
  ["HCV - Navegadores En Red Y Hospital Digital","Administrativa","Marcela Tobar","356353",""],
  ["HCV - Navegadores En Red Y Hospital Digital","Digitadora","Maria Elizabeth Espinoza","356272","maria.espinoza.n@redsalud.gob.cl"],
  ["HCV - Navegadores En Red Y Hospital Digital","Digitadora","Priscila Caceres","356437","priscilla.caceres.t@redsalud.gob.cl"],
  ["HCV - Oficina De Partes","Administrativo","Ana Luisa Serrano","356167","ana.serrano@redsalud.gob.cl"],
  ["HCV - Oficina De Partes","Jefatura","Maria Araya Jeria","356199","oficinadepartes.hcv@redsalud.gob.cl"],
  ["HCV - OIRS","Secretaria","Blanca Vera","356171","blanca.vera@redsalud.gob.cl"],
  ["HCV - OIRS","Trabajador Social","Claudio Plaza","353107","claudio.plaza@redsalud.gob.cl"],
  ["HCV - OIRS","Jefatura","Joanna Carrasco","356170","joanna.carrasco@redsalud.gob.cl"],
  ["HCV - OIRS","Gestión De Requerimiento, Piso Zócalo","Margarita Farias","353025","margarita.farias.r@redsalud.gob.cl"],
  ["HCV - OIRS","Gestión De Requerimientos, Piso 3","Paola Abarca Arce","356296","paola.abarca.a@redsalud.gov.cl"],
  ["HCV - OIRS","Hospitalizados SC Aislamiento, Piso 3","Personal De Turno","353162","oirscentral.hcv@redsalud.gob.cl"],
  ["HCV - OIRS","Hospitalizados SC Médico Quirúrgico, Piso 1","Personal De Turno","356344","oirscentral.hcv@redsalud.gob.cl"],
  ["HCV - OIRS","Hospitalizados SC Médico Quirúrgico, Piso 2","Personal De Turno","353163","oirscentral.hcv@redsalud.gob.cl"],
  ["HCV - OIRS","Hospitalizados SC Obstetricia Y Parto Integral, Piso 2.","Personal De Turno","353164","oirscentral.hcv@redsalud.gob.cl"],
  ["HCV - OIRS","Hospitalizados SC Pediatría, Piso 3","Personal De Turno","353162","oirscentral.hcv@redsalud.gob.cl"],
  ["HCV - OIRS","Informaciones Piso 2 H. Antiguo (PRAIS)","Personal De Turno","353209",""],
  ["HCV - OIRS","Mesón Principal","Personal De Turno","356172","oirscae.hcv@redsalud.gob.cl"],
  ["HCV - OIRS","Mesón Principal","Personal De Turno","356174","oirscae.hcv@redsalud.gob.cl"],
  ["HCV - OIRS","Salud Mental Casa De Colores","Personal De Turno","353024",""],
  ["HCV - OIRS","Urgencias","Personal De Turno 24 Horas","356175","oirs.hcv.urgencias@gmail.com"],
  ["HCV - OIRS","Gestión De Requerimiento, Piso Zócalo","Rodrigo Parra","353025","rodrigo.parra@redsalud.gob.cl"],
  ["HCV - Pabellón","Pabellón pasillo","","353177",""],
  ["HCV - Pabellón","FAP","FAP","356431",""],
  ["HCV - Pabellón","Administrativa","Lina Velasquez","356435",""],
  ["HCV - Pabellón","Jefatura","Luis Jara","353170","luis.jara@redsalud.gob.cl"],
  ["HCV - Pabellón","Pabellon Recuperación","Pabellon","353180","sergio.reyesvi@redsalud.gov.cl"],
  ["HCV - Pabellón","Pabellon Recuperación","Pabellon","373180",""],
  ["HCV - Pabellón","Pasillo","Pasillo","356433",""],
  ["HCV - Pabellón","Enfermero Jefe","Sergio Reyes","353179","sergio.reyesvi@redsalud.gob.cl"],
  ["HCV - Pabellón","Secretaria","Sulamita Silva Mesina","356434","sulamita.silva@redsalud.gob.cl"],
  ["HCV - PRAIS","Encargada","Andrea Alvarez G.","353065","andrea.alvarezg@redsalud.gob.cl"],
  ["HCV - PRAIS","Secretaria","Jenny Berrios Farías","356433","jenny.berrios@redsalud.gob.cl"],
  ["HCV - PRAIS","PRAIS-Psicóloga","Verónica Mira","353217","veronica.mira@redsalud.gob.cl"],
  ["HCV - Prevención De Riesgos","Técnico","Alexis Ladron De Guevara","353083","alexis.ladrondeguevara@redsalud.gob.cl"],
  ["HCV - Prevención De Riesgos","Jefatura","Hernan Godoy Céspedes","353083","hernan.godoy@redsalud.gob.cl"],
  ["HCV - Prevención De Riesgos","Tecnico","Idiana Espinoza","353083","idiana.espinoza.g@redsalud.gob.cl"],
  ["HCV - Proyectos Y Puesta En Marcha","Enfermera","Andrea Sanhueza","353098","andrea.sanhuezan@redsalud.gob.cl"],
  ["HCV - Proyectos Y Puesta En Marcha","Profesional","Daniel Olivares","353098",""],
  ["HCV - RAD","Encargado","Vanesa Cabrera C","353155","vanesa.cabrera.c@redsalud.gob.cl"],
  ["HCV - RAD","Jefatura","Vanessa Cabrera","353155","vanesa.cabrera.c@redsalud.gob.cl"],
  ["HCV - Recaudación","Cobranzas","Claudia Araya Cornejo","356223","claudia.arayacornejo@redsalud.gob.cl"],
  ["HCV - Recaudación","Secretaria","Claudia Gamboa Vidal","356228","claudia.gamboa@redsalud.gob.cl"],
  ["HCV - Recaudación","Jefatura","Cristian Rodriguez","356220","cristian.rodriguezr@redsalud.gob.cl"],
  ["HCV - Recaudación","Jefatura (s)","Fabiola Jorquera","356424","fabiola.jorquera@redsalud.gob.cl"],
  ["HCV - Recaudación","Cobranzas","Felipe Vidal","356221","felipe.vidala@redsalud.gob.cl"],
  ["HCV - Recaudación","Central","Gloria Salinas","353105","gloria.salinasd@redsalud.gob.cl"],
  ["HCV - Recaudación","Central","Gloria Salinas","356227",""],
  ["HCV - Recaudación","Cobranzas","Salome Aedo","356222","salome.aedo@redsalud.gob.cl"],
  ["HCV - Recaudación","Urgencia Adulto","Urgencia Adulto","356225",""],
  ["HCV - Reclutamiento y Selección","Jefatura","Alejandro Parra Reyes","356451",""],
  ["HCV - Reclutamiento y Selección","Administrativo","Aylin Martinez Calderon","356365","reclutamiento.hcv@redsalud.gob.cl"],
  ["HCV - Reclutamiento y Selección","Psicólogo Reclutador","Benjamin Zamora Cruz","356365","reclutamiento.hcv@redsalud.gob.cl"],
  ["HCV - Reclutamiento y Selección","Profesional","Cristopher Paine","356365","cristopher.paine@redsalud.gob.cl"],
  ["HCV - Reclutamiento y Selección","Psicólogo","Yerco Escobar","356365",""],
  ["HCV - Lista Espera","Registro","Pablo Nuñez Loyola","356268","pablo.nunez@redsalud.gob.cl"],
  ["HCV - Salud Funcionarios","Secretaria","Marcela Contreras","356234","marcela.contrerash@redsalud.gob.cl"],
  ["HCV - Salud Funcionarios","Jefatura","María Fernanda Mendoza","353060","maria.mendoza@redsalud.gob.cl"],
  ["HCV - Salud Mental Casa Azul","Box Psicóloga","Cecilia Gonzalez","353204","uberlinda.gutierrez.i@redsalud.gob.cl"],
  ["HCV - Salud Mental Casa Azul","Enfermera - Tens","Gabriela Cerda - Daniela Gamboa","353206","gabriela.cerda.c@redsalud.gob.cl"],
  ["HCV - Salud Mental Casa Azul","Terapeuta Ocupacional","Jennifer Pastrian","353200","jennifer.pastrian@redsalud.gob.cl"],
  ["HCV - Salud Mental Casa Azul","Coordinador Programa Adicciones","Jorge Saavedra","353201","jorge.saavedrag@redsalud.gob.cl"],
  ["HCV - Salud Mental Casa Azul","Profesionales Medicos","Psiquiatra - Medico General","353203","uberlinda.gutierrez.i@redsalud.gob.cl"],
  ["HCV - Salud Mental Casa Azul","Administrativa /Ing","Uberlinda Gutierrez","353205","uberlinda.gutierrez.i@redsalud.gob.cl"],
  ["HCV - Salud Mental Casa Blanca","Hospital Diurno","Fernando Gonzalez","552540080 local",""],
  ["HCV - Salud Mental Casa Blanca","Digitador","Francisco Lopez Muga","353214","francisco.lopez@redsalud.gob.cl"],
  ["HCV - Salud Mental Casa Blanca","Jefatura","Mauricio Muñoz","353160","mauricio.munozp@redsalud.gob.cl"],
  ["HCV - Salud Mental Casa Blanca","Enfermera","Solange Fernandez","353212","solange.fernandez@redsalud.gob.cl"],
  ["HCV - Salud Mental Infanto Juvenil","Administrativa","Celeste San Martin","356460","celeste.sanmartin.e@redsalud.gob.cl"],
  ["HCV - Salud Mental Infanto Juvenil","Tens","Danitza Nuñez","356466","recetasinfanto.hcv@gmail.com"],
  ["HCV - Salud Mental Infanto Juvenil","Jefatura","Gisela Palma","356465","gisela.palma@redsalud.gob.cl"],
  ["HCV - Salud Ocupacional","Jefatura","Enrique Carrasco","356235","enrique.carrascoa@redsalud.gob.cl"],
  ["HCV - Salud Ocupacional","Profesional","Teresa Salvatierra","353082","teresa.salvatierra@redsalud.gob.cl"],
  ["HCV - Aislamiento","Secretaria","Carmen Bustos","353152",""],
  ["HCV - Aislamiento","Enfermera Supervisora","Katherine Marin","356217",""],
  ["HCV - Aislamiento","Estación Enfermería","Personal de Turno","356218",""],
  ["HCV - Médico Quirúrgico","Secretaria","Ana Gonzalez Acuña","356291","ana.gonzalez@redsalud.gob.cl"],
  ["HCV - Médico Quirúrgico","Enfermera Supervisora","Carol Farias","356294","carol.fariasj@redsalud.gob.cl"],
  ["HCV - Médico Quirúrgico","Jefatura Medicina","Dr. Omar Pujol","356290",""],
  ["HCV - Médico Quirúrgico","Jefatura Cirugía","Dra. Gabriela Espinoza","356300",""],
  ["HCV - Médico Quirúrgico","Piso 1, Sala de Informe Medico","Informe Medico","353166",""],
  ["HCV - Médico Quirúrgico","Secretaria","Karina Villacura","356291","karina.villacura.r@redsalud.gob.cl"],
  ["HCV - Médico Quirúrgico","Piso 2, enfermera supervisora","Lilian Gutierrez","356304","lilian.gutierrez@redsalud.gob.cl"],
  ["HCV - Médico Quirúrgico","Piso 2, secretaria","Marisol Rojas","356301","marisol.rojas.o@redsalud.gob.cl"],
  ["HCV - Médico Quirúrgico","Piso 1 Ala Norte / Sala 1 a la 12","Personal de Turno","353165","mq.hcv.2023@gmail.com"],
  ["HCV - Médico Quirúrgico","Piso 1 Ala Sur / Sala 13 a la 24","Personal de Turno","356292",""],
  ["HCV - Médico Quirúrgico","Piso 1 Ala Sur / Sala 13 a la 24","Personal de Turno","356293",""],
  ["HCV - Médico Quirúrgico","Piso 2 ex Cirugía","Personal de Turno","356303",""],
  ["HCV - Médico Quirúrgico","Piso 2 ex Cirugía","Personal de Turno","356302",""],
  ["HCV - Neonatología","Jefatura","Dra. Camila Carrasco","356326","camila.carrasco.r@redsalud.gob.cl"],
  ["HCV - Neonatología","Piso 2 NHCV","Matrona de turno","356326",""],
  ["HCV - Obstetricia","Matrona Supervisora","Camilla Infante","356308","camilla.infante@redsalud.gov.cl"],
  ["HCV - Obstetricia","Gestora del Cuidado Matronería","Daisy Badilla Meneses","356319","daisy.badilla@redsalud.gob.cl"],
  ["HCV - Obstetricia","Jefatura","Dr. Luis Alfonso Fuentes","356310","alfonso.fuentes@redsalud.gob.cl"],
  ["HCV - Obstetricia","Secretaria Gestión Cuidado Matronería","Fabiola Gonzalez","356319","fabiola.gonzalez.so@redsalud.gob.cl"],
  ["HCV - Obstetricia","Educadora De Párvulos","Karla Farias","353148","karla.farias.g@redsalud.gob.cl"],
  ["HCV - Obstetricia","Trabajadora Social","Lorena Lucero","353116","lorena.lucero@redsalud.gov.cl"],
  ["HCV - Obstetricia","Pre-Parto","Matrones de Turno","356315","hcv.maternidadparto@gmail.com"],
  ["HCV - Obstetricia","Secretaria","Noelia Acevedo","356318","noelia.acevedo@redsalud.gob.cl"],
  ["HCV - Obstetricia","Estacion Matronería","Personal de Turno","356317",""],
  ["HCV - Obstetricia","Estar Auxiliar","Personal de Turno","356313",""],
  ["HCV - Pediatría","Secretaria","Ana Alvarado","356320","ana.alvarado@redsalud.gob.cl"],
  ["HCV - Pediatría","Jefatura","Dra. Rossana Madrid Muñoz","356186","rossana.madrid@redsalud.gob.cl"],
  ["HCV - Pediatría","Estacion De Enfermeria","Estacion De Enfermeria","356322",""],
  ["HCV - Pediatría","Enfermera Supervisora","Yany Palomino","356323","yany.palomino@redsalud.gob.cl"],
  ["HCV - Servicio Social","","Carolina Salas","356192","carolina.salaso@redsalud.gob.cl"],
  ["HCV - Servicio Social","","Francisca Perotti","356209","francisca.perotti@redsalud.gob.cl"],
  ["HCV - Servicio Social","Jefatura","Lilian Ponce","356193","lilian.ponce.ro@redsalud.gov.cl"],
  ["HCV - Servicio Social","","Nice Espina","356209","nice.espina@redsalud.gov.cl"],
  ["HCV - Servicio Social","Atencion Abierta","Rhode Martinez","353172","rhode.martinez.f@redsalud.gob.cl"],
  ["HCV - Servicios Generales","Ropería","Alejandro Mella","356250","alejandro.mella@redsalud.gob.cl"],
  ["HCV - Servicios Generales","Ropería","Area Limpia","356251",""],
  ["HCV - Servicios Generales","Ropería","Confeccion","356249",""],
  ["HCV - Servicios Generales","Jefatura","Daniel Roa","356240","daniel.roa@redsalud.gob.cl"],
  ["HCV - Servicios Generales","Administrativo","Mirta Vera","356241","mirta.vera@redsalud.gob.cl"],
  ["HCV - Servicios Generales","Contratista Equipos Médicos","Oscar Gonzalez","994348151","oscar.gonzalezv@redsalud.gob.cl"],
  ["HCV - Servicios Generales","Encargado Parque Automotriz","Stevens Espina","356242","stevens.espina@redsalud.gob.cl"],
  ["HCV - SIDRA","Mantenedor SIDRA","Alejandra Riveros","356262","alejandra.riveros@redsalud.gob.cl"],
  ["HCV - SIDRA","Mantenedor SIDRA","Carlos Maldonado","356261","carlos.maldonadop@redsalud.gob.cl"],
  ["HCV - SIDRA","Jefatura","Luz Urbina","356260","luz.urbina@redsalud.gob.cl"],
  ["HCV - SIDRA","Profesional","Solange Plaza","353100","solange.plaza@redsalud.gob.cl"],
  ["HCV - SIGCOM","Coordinador","Luis Diaz","Sin anexo","luis.diazg@redsalud.gob.cl"],
  ["HCV - Subdirección Apoyo Diagnostico Y Terapeutico","Jefatura","Dr. Marco Vargas Lazo","356169","marco.vargas@redsalud.gob.cl"],
  ["HCV - Subdirección Gestión Administrativa Y Financiera","Jefatura","Javier Rojas R.","356196","javier.rojasr@redsalud.gob.cl"],
  ["HCV - Subdirección Gestión Administrativa Y Financiera","Secretaria","Silvia Olivera","356246","silvia.olivera.d@redsalud.gob.cl"],
  ["HCV - Subdirección Gestión Asistencial","Jefatura","Dra. Jeanette Vega","353157",""],
  ["HCV - Subdirección Gestión Asistencial","Secretaria","Romina Gamboa Hormazabal","356164","romina.gamboa@redsalud.gob.cl"],
  ["HCV - Subdirección Gestión De Operaciones","Jefatura","Hector Araneda","356404","hector.araneda@redsalud.gob.cl"],
  ["HCV - Subdirección Gestión De Operaciones","Secretaria","Jessica Hernández G.","356461","jessica.hernandezg@redsalud.gob.cl"],
  ["HCV - Subdirección Gestión De Operaciones","Secretaria","Maria Jose Duarte","356339","mariajose.duarte@redsalud.gov.cl"],
  ["HCV - Subdirección Gestión De Operaciones","Jefe","Rodrigo Piña Arratia","356407","rodrigo.pina@redsalud.gov.cl"],
  ["HCV - Subdirección Gestión De Usuarios","Inclusión","Claudia Ugarte","356182","claudia.ugarte@redsalud.gov.cl"],
  ["HCV - Subdirección Gestión De Usuarios","Jefatura","Natalia Jara","356305","natalia.jara.s@redsalud.gob.cl"],
  ["HCV - Subdirección Gestión Del Cuidado","Jefatura","Alfonso Ramos Reyes","356422","alfonso.ramos@redsalud.gob.cl"],
  ["HCV - Subdirección Gestión Del Cuidado","Secretaria","Angela Farias","356422","angela.farias.c@redsalud.gov.cl"],
  ["HCV - Subdirección Gestión Y Desarrollo De Las Personas","Secretaria","Andrea Alvarez","356239","andrea.alvarezr@redsalud.gob.cl"],
  ["HCV - Subdirección Gestión Y Desarrollo De Las Personas","Jefatura","Maria De Los Angeles Massardo","356311","maria.massardo@redsalud.gob.cl"],
  ["HCV - UCI","Médico Jefe","Dra. Malinali Montoya","353159",""],
  ["HCV - UCI","Estación de enfermería","Enfermera","353198",""],
  ["HCV - UTI","Jefatura","Dr. Alex Gomez Macías","356159","alex.gomez@redsalud.gob.cl"],
  ["HCV - UTI","Secretaria","Karina Martínez Calderón","353158","karina.martinez@redsalud.gob.cl"],
  ["HCV - UTI","Enfermera Supervisora","Macarena Donoso Carvajal","356298","macarena.donoso@redsalud.gob.cl"],
  ["HCV - UTI","Enfemera","Personal de Turno","356297",""],
  ["HCV - SAMU","Secretaria","Ingrid Tapia","356252","ingrid.tapia@redsalud.gob.cl"],
  ["HCV - SAMU","Reanimador","Reanimador de turno","356410",""],
  ["HCV - Servicio Sociosanitario","Enfermera Supervisora","Tania Arellano","353144","tania.arellano.r@redsalud.gob.cl"],
  ["SSVSA - Informática","","Andres Moya","326702",""],
  ["SSVSA - Lista de Espera","","Astrid","326565",""],
  ["SSVSA - Informática","","Carlos Jorquera","324861",""],
  ["SSVSA - Jurídica","Secretaria","Debora Bustos Muñoz","326582","debora.bustos@redsalud.gov.cl"],
  ["SSVSA - SIDRA","Jefatura","Dr. Marcelo Castro","326367","marcelo.castrom@redsalud.gob.cl"],
  ["SSVSA - SIDRA","","Erik Cuevas","326368",""],
  ["SSVSA - Subdepartamento De Ingeniería","","Fernando Rojas Faune","326646","fernando.rojasf@redsalud.gob.cl"],
  ["SSVSA - Procura","Procura","Gricel Zamorano","326982",""],
  ["SSVSA - Informática","Encargado Cyberseguridad","Guillermo Riveros Figueroa","326750","guillermo.riveros@redsalud.gob.cl"],
  ["SSVSA - Informática","Secretaria","Ingrid","326578",""],
  ["SSVSA - Jurídica","Abogado","Javier Valenzuela","326584",""],
  ["SSVSA - Jurídica","Abogado","Jose Miguel Quiroz","326582","josemiguel.quirozm@redsalud.gov.cl"],
  ["SSVSA - Sudais","","Kareen Schiappaccase","326635",""],
  ["SSVSA - Informatica","","Manuel Soto","326574","manuelsoto@redsalud.gov.cl"],
  ["SSVSA - Coordinador SSVSA","","Mario Vergara (matron)","324095","mario.vergara@redsalud.gov.cl"],
  ["SSVSA - Informatica","","Ruth Alvarez","326579",""],
  ["SSVSA - SUDAIS","","Susana Uribe","326636",""],
  ["SSVSA - Informática","Jefatura","Victor Monsalve","326579",""],
  ["SSVSA - SIDRA","","Virginia Campos","326366",""],
  ["SSVSA - SIDRA","","Yonathan Rozas","321119",""]
];
