export const DOM = {

    /* perfiles */
    profiles: document.getElementById("profiles"),
    profileSearch: document.getElementById("profileSearch"),
    emptyProfiles: document.getElementById("emptyProfiles"),
    filterRole: document.getElementById("filterRole"),
    showInactiveProfiles: document.getElementById("showInactiveProfiles"),
    openCreateProfileBtn: document.getElementById("openCreateProfile"),
    openEditProfileBtn: document.getElementById("openEditProfile"),
    workerAppInviteBtn: document.getElementById("workerAppInviteBtn"),
    workerLinkStatusBtn: document.getElementById("workerLinkStatusBtn"),

    /* formulario perfil */
    profileNameInput: document.getElementById("profileNameField"),
    profileEmailInput: document.getElementById("profileEmailField"),
    profileEmailHint: document.getElementById("profileEmailHint"),
    profileRutInput: document.getElementById("profileRutField"),
    profilePhoneInput: document.getElementById("profilePhoneField"),
    profileBirthDateInput: document.getElementById("profileBirthDateField"),
    profileDocsInput: document.getElementById("profileDocsField"),
    profileDocsList: document.getElementById("profileDocsList"),
    profileActiveToggle: document.getElementById("profileActiveToggle"),
    profileUnitEntryDateRow: document.getElementById("profileUnitEntryDateRow"),
    profileUnitEntryDateInput: document.getElementById("profileUnitEntryDateField"),
    profileContractTypeSelect: document.getElementById("profileContractTypeField"),
    profileRoleSelect: document.getElementById("profileRoleField"),
    profileProfessionSelect: document.getElementById("profileProfessionField"),
    profileProfessionCustomInput: document.getElementById("profileProfessionCustomField"),
    profileProfessionOptions: document.getElementById("profileProfessionOptions"),
    profileRotationSelect: document.getElementById("profileRotationField"),
    profileRotationRow: document.getElementById("profileRotationRow"),
    profileRotationAnchor: document.getElementById("profileRotationAnchor"),
    profileUnionLeaveInput: document.getElementById("profileUnionLeaveField"),
    profileUnionLeaveRow: document.getElementById("profileUnionLeaveRow"),
    shiftAssignedRow: document.getElementById("shiftAssignedRow"),
    profileGradeRow: document.getElementById("profileGradeRow"),
    profileGradeSelect: document.getElementById("profileGradeField"),
    profileRotationStatus: document.getElementById("profileRotationStatus"),
    replacementContractEditor: document.getElementById("replacementContractEditor"),
    replacementTargetInput: document.getElementById("replacementTargetField"),
    replacementReasonSelect: document.getElementById("replacementReasonField"),
    replacementContractStatus: document.getElementById("replacementContractStatus"),
    honorariaContractEditor: document.getElementById("honorariaContractEditor"),
    honorariaRotationSlot: document.getElementById("honorariaRotationSlot"),
    honorariaContractStatus: document.getElementById("honorariaContractStatus"),
    honorariaContractList: document.getElementById("honorariaContractList"),
    honorariaAddContractBtn: document.getElementById("honorariaAddContractBtn"),
    profileContractHistory: document.getElementById("profileContractHistory"),
    profileEditorHint: document.getElementById("profileEditorHint"),
    profileRecordsPanel: document.getElementById("profileRecordsPanel"),

    /* config */
    checkbox: document.getElementById("shiftAssigned"),
    authUserChip: document.getElementById("authUserChip"),
    authUserName: document.getElementById("authUserName"),
    mobileMenuToggle: document.getElementById("mobileMenuToggle"),
    themeToggle: document.getElementById("themeToggle"),
    plansBtn: document.getElementById("plansBtn"),
    systemSettingsBtn: document.getElementById("systemSettingsBtn"),
    floatingMessagesBtn: document.getElementById("floatingMessagesBtn"),
    floatingMessagesBadge: document.getElementById("floatingMessagesBadge"),

    /* botones turnos */
    adminBtn: document.getElementById("adminBtn"),
    adminBtnLabel: document.getElementById("adminBtnLabel"),
    halfAdminMorningBtn: document.getElementById("halfAdminMorningBtn"),
    halfAdminAfternoonBtn: document.getElementById("halfAdminAfternoonBtn"),
    legalBtn: document.getElementById("legalBtn"),
    legalBtnLabel: document.getElementById("legalBtnLabel"),
    compBtn: document.getElementById("compBtn"),
    compBtnLabel: document.getElementById("compBtnLabel"),
    licenseBtn: document.getElementById("licenseBtn"),
    professionalLicenseBtn: document.getElementById("professionalLicenseBtn"),
    unionLeaveBtn: document.getElementById("unionLeaveBtn"),
    unpaidLeaveBtn: document.getElementById("unpaidLeaveBtn"),
    hoursReturnBtn: document.getElementById("hoursReturnBtn"),
    hoursReturnBtnLabel: document.getElementById("hoursReturnBtnLabel"),
    unjustifiedAbsenceBtn: document.getElementById("unjustifiedAbsenceBtn"),
    clockMarkBtn: document.getElementById("clockMarkBtn"),
    trainingBtn: document.getElementById("trainingBtn"),
    moveShiftBtn: document.getElementById("moveShiftBtn"),

    /* navegacion */
    prevBtn: document.getElementById("prevBtn"),
    nextBtn: document.getElementById("nextBtn"),
    calendarRotationButton: document.getElementById("calendarRotationButton"),
    undoBtn: document.getElementById("undoBtn"),
    redoBtn: document.getElementById("redoBtn"),
    mobileLeaveToggle: document.getElementById("mobileLeaveToggle"),

    /* paneles */
    selectorInfo: document.getElementById("selectorInfo"),
    adminInfo: document.getElementById("adminInfo"),
    calendar: document.getElementById("calendar"),
    reportsProfileSearch: document.getElementById("reportsProfileSearch"),
    reportsFilterRole: document.getElementById("reportsFilterRole"),
    reportsShowInactiveProfiles: document.getElementById("reportsShowInactiveProfiles"),
    reportsProfiles: document.getElementById("reportsProfiles"),
    reportsEmptyProfiles: document.getElementById("reportsEmptyProfiles"),
    reportsSelectedInfo: document.getElementById("reportsSelectedInfo"),
    report4TurnoNoAssignmentCard: document.getElementById("report4TurnoNoAssignmentCard"),
    report4TurnoNoAssignmentTitle: document.getElementById("report4TurnoNoAssignmentTitle"),
    report4TurnoNoAssignmentPreview: document.getElementById("report4TurnoNoAssignmentPreview"),
    downloadNoAssignmentReportBtn: document.getElementById("downloadNoAssignmentReportBtn"),
    printReportPdfBtn: document.getElementById("printReportPdfBtn"),
    printTensReportBtn: document.getElementById("printTensReportBtn"),
    printCoverageAuthorizationBtn: document.getElementById("printCoverageAuthorizationBtn"),
    reportsUnavailableHint: document.getElementById("reportsUnavailableHint"),
    dashboardPanel: document.getElementById("dashboardPanel"),
    teamTimeline: document.getElementById("teamTimeline"),
    swapPanel: document.getElementById("swapPanel"),
    workerRequestsPanel: document.getElementById("workerRequestsPanel"),
    memosPanel: document.getElementById("memosPanel"),
    availabilitySummary: document.getElementById("availabilitySummary"),
    profileAvailabilityCard: document.getElementById("profileAvailabilityCard"),
    availabilityEditBtn: document.getElementById("availabilityEditBtn"),
    printHoursReportBtn: document.getElementById("printHoursReportBtn"),
    hheePrevMonthBtn: document.getElementById("hheePrevMonth"),
    hheeNextMonthBtn: document.getElementById("hheeNextMonth"),
    hheeMonthLabel: document.getElementById("hheeMonthLabel"),
    hheeReturnTransferToggle: document.getElementById("hheeReturnTransferToggle"),
    hheeReturnTransferInfo: document.getElementById("hheeReturnTransferInfo"),
    hheeProfileSearch: document.getElementById("hheeProfileSearch"),
    hheeFilterRole: document.getElementById("hheeFilterRole"),
    hheeShowInactiveProfiles: document.getElementById("hheeShowInactiveProfiles"),
    hheeProfiles: document.getElementById("hheeProfiles"),
    hheeEmptyProfiles: document.getElementById("hheeEmptyProfiles"),
    hheeChartRole: document.getElementById("hheeChartRole"),
    hheeChartMonth: document.getElementById("hheeChartMonth"),
    hheeHistoryYears: document.getElementById("hheeHistoryYears"),
    hheeMonthlyChart: document.getElementById("hheeMonthlyChart"),
    hheeHistoryChart: document.getElementById("hheeHistoryChart"),
    hheeProfileHistoryChart: document.getElementById("hheeProfileHistoryChart"),
    hheeMonthlyRecords: document.getElementById("hheeMonthlyRecords"),

    /* buscador superior */
    topProfileSearchForm: document.getElementById("topProfileSearchForm"),
    topProfileSearchInput: document.getElementById("topProfileSearch"),
    topProfileOptions: document.getElementById("topProfileOptions"),
    calendarDirectEditToggle: document.getElementById("calendarDirectEditToggle")
};
